@startuml
class AuthDependencyInjection <<static>> {
    + {static} AddCustomAuthentication(services:IServiceCollection, configuration:IConfiguration) : IServiceCollection
    + {static} AddCustomAuthorization(services:IServiceCollection) : IServiceCollection
}
@enduml
