@startuml
class MovieTypeConfiguration {
    + Configure(builder:EntityTypeBuilder<Movie>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<Movie>" <|-- MovieTypeConfiguration
@enduml
