@startuml
class ReservationTypeConfiguration {
    + Configure(builder:EntityTypeBuilder<Reservation>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<Reservation>" <|-- ReservationTypeConfiguration
@enduml
