@startuml
class SessionTypeConfiguration {
    + Configure(builder:EntityTypeBuilder<Session>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<Session>" <|-- SessionTypeConfiguration
@enduml
