@startuml
!include .\\.\src\LightCinema.Data\ApplicationDbContext.puml
!include .\\.\src\LightCinema.Data\SeedData.puml
!include .\\.\src\LightCinema.WebApi\Program.puml
!include .\\.\src\LightCinema.Data\Entities\Country.puml
!include .\\.\src\LightCinema.Data\Entities\Genre.puml
!include .\\.\src\LightCinema.Data\Entities\Movie.puml
!include .\\.\src\LightCinema.Data\Entities\Reservation.puml
!include .\\.\src\LightCinema.Data\Entities\Seat.puml
!include .\\.\src\LightCinema.Data\Entities\Session.puml
!include .\\.\src\LightCinema.Data\Entities\User.puml
!include .\\.\src\LightCinema.Data\Migrations\20231213162438_Initial.puml
!include .\\.\src\LightCinema.Data\Migrations\20231213162438_Initial.Designer.puml
!include .\\.\src\LightCinema.Data\Migrations\ApplicationDbContextModelSnapshot.puml
!include .\\.\src\LightCinema.Data\TypeConfigurations\CountryTypeConfiguration.puml
!include .\\.\src\LightCinema.Data\TypeConfigurations\GenreTypeConfiguration.puml
!include .\\.\src\LightCinema.Data\TypeConfigurations\MovieTypeConfiguration.puml
!include .\\.\src\LightCinema.Data\TypeConfigurations\ReservationTypeConfiguration.puml
!include .\\.\src\LightCinema.Data\TypeConfigurations\SeatTypeConfiguration.puml
!include .\\.\src\LightCinema.Data\TypeConfigurations\SessionTypeConfiguration.puml
!include .\\.\src\LightCinema.Data\TypeConfigurations\UserTypeConfiguration.puml
!include .\\.\src\LightCinema.WebApi\Controllers\BaseController.puml
!include .\\.\src\LightCinema.WebApi\Application\Auth\AuthDependencyInjection.puml
!include .\\.\src\LightCinema.WebApi\Application\Auth\PolicyNames.puml
!include .\\.\src\LightCinema.WebApi\Application\Auth\RoleNames.puml
!include .\\.\src\LightCinema.WebApi\Application\Configs\JwtConfig.puml
!include .\\.\src\LightCinema.WebApi\Application\Exceptions\AccessDeniedException.puml
!include .\\.\src\LightCinema.WebApi\Application\Exceptions\AuthenticationException.puml
!include .\\.\src\LightCinema.WebApi\Application\Exceptions\BaseException.puml
!include .\\.\src\LightCinema.WebApi\Application\Exceptions\BusinessException.puml
!include .\\.\src\LightCinema.WebApi\Application\Exceptions\NotFoundException.puml
!include .\\.\src\LightCinema.WebApi\Application\Exceptions\ValidationException.puml
!include .\\.\src\LightCinema.WebApi\Application\Filters\ExceptionFilter.puml
!include .\\.\src\LightCinema.WebApi\Application\Filters\ValidationFilter.puml
!include .\\.\src\LightCinema.WebApi\Application\Middlewares\ExceptionMiddleware.puml
!include .\\.\src\LightCinema.WebApi\Application\Services\JwtService.puml
!include .\\.\src\LightCinema.WebApi\Application\Swagger\ConfigureSwaggerOptions.puml
!include .\\.\src\LightCinema.WebApi\Application\Swagger\SwaggerDependencyInjection.puml
!include .\\.\src\LightCinema.WebApi\Controllers\Halls\HallsController.puml
!include .\\.\src\LightCinema.WebApi\Controllers\Movies\MoviesController.puml
!include .\\.\src\LightCinema.WebApi\Controllers\Sessions\SessionsController.puml
!include .\\.\src\LightCinema.WebApi\Controllers\Users\UsersController.puml
!include .\\.\src\LightCinema.Data\obj\Debug\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\.\src\LightCinema.Data\obj\Debug\net7.0\LightCinema.Data.AssemblyInfo.puml
!include .\\.\src\LightCinema.Data\obj\Debug\net7.0\LightCinema.Data.GlobalUsings.g.puml
!include .\\.\src\LightCinema.WebApi\Controllers\Halls\DTO\CreateHallRequest.puml
!include .\\.\src\LightCinema.WebApi\Controllers\Halls\DTO\GetHallsResponse.puml
!include .\\.\src\LightCinema.WebApi\Controllers\Movies\DTO\CreateMovieRequest.puml
!include .\\.\src\LightCinema.WebApi\Controllers\Movies\DTO\DateType.puml
!include .\\.\src\LightCinema.WebApi\Controllers\Movies\DTO\GetCountriesResponse.puml
!include .\\.\src\LightCinema.WebApi\Controllers\Movies\DTO\GetGenresResponse.puml
!include .\\.\src\LightCinema.WebApi\Controllers\Movies\DTO\GetMovieResponse.puml
!include .\\.\src\LightCinema.WebApi\Controllers\Movies\DTO\GetMoviesResponse.puml
!include .\\.\src\LightCinema.WebApi\Controllers\Movies\DTO\UpdateMovieRequest.puml
!include .\\.\src\LightCinema.WebApi\Controllers\Sessions\DTO\CreateSessionRequest.puml
!include .\\.\src\LightCinema.WebApi\Controllers\Sessions\DTO\GetSeatsBySessionResponse.puml
!include .\\.\src\LightCinema.WebApi\Controllers\Sessions\DTO\GetSessionByIdResponse.puml
!include .\\.\src\LightCinema.WebApi\Controllers\Sessions\DTO\ReserveRequest.puml
!include .\\.\src\LightCinema.WebApi\Controllers\Sessions\DTO\UnreserveRequest.puml
!include .\\.\src\LightCinema.WebApi\Controllers\Users\DTO\AuthResponse.puml
!include .\\.\src\LightCinema.WebApi\Controllers\Users\DTO\ClientErrorResponse.puml
!include .\\.\src\LightCinema.WebApi\Controllers\Users\DTO\ProfileResponse.puml
!include .\\.\src\LightCinema.WebApi\Controllers\Users\DTO\RefreshRequest.puml
!include .\\.\src\LightCinema.WebApi\Controllers\Users\DTO\ServerErrorResponse.puml
!include .\\.\src\LightCinema.WebApi\Controllers\Users\DTO\UserLoginRequest.puml
!include .\\.\src\LightCinema.WebApi\Controllers\Users\DTO\UserRegisterRequest.puml
!include .\\.\src\LightCinema.WebApi\Controllers\Users\DTO\UserResponse.puml
!include .\\.\src\LightCinema.WebApi\obj\Debug\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\.\src\LightCinema.WebApi\obj\Debug\net7.0\LightCinema.WebApi.AssemblyInfo.puml
!include .\\.\src\LightCinema.WebApi\obj\Debug\net7.0\LightCinema.WebApi.GlobalUsings.g.puml
!include .\\.\src\LightCinema.WebApi\obj\Debug\net7.0\LightCinema.WebApi.MvcApplicationPartsAssemblyInfo.puml
@enduml
